### PR TITLE
Fixing duplicate schemes issue

### LINKED ISSUE #3308: apollo-ios-xcframework is built twice by Carthage
### Summary

When `apollo-ios-xcframework` is added as a dependency using Carthage, it is built two times even though it only produces one framework.

### Version

1.7.1

### Steps to reproduce the behavior

- Add `apollographql/apollo-ios-xcframework` as a Carthage dependency in a project.
- Run `carthage build`
- See that it builds Apollo twice.

### Logs

```shell
*** Building scheme "Apollo" in Apollo.xcworkspace
*** Building scheme "Apollo" in Apollo.xcworkspace
```

### Anything else?

It appears to be caused by there being two schemes in the workspace with the name `Apollo`. Running `xcodebuild -list` in the repo shows the following.
```
Information about project "Apollo":
    Targets:
        Apollo
        ApolloAPI
        ApolloSQLite
        ApolloWebSocket

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Apollo
        Apollo
        Apollo-Dynamic
        ApolloAPI
        ApolloSQLite
        ApolloTestSupport
        ApolloWebSocket
        InstallCLI
```

One is the shared scheme in the project and the other is autogenerated from the swift package target also called `Apollo`. Carthage then builds each scheme it finds that has the same name as a shared scheme in the project. Since two have the same name, it builds them twice.

A workaround seems to be renaming the scheme before running Carthage, then there's only one listed scheme that matches the name of a shared scheme.

```bash
mv Carthage/Checkouts/apollo-ios-xcframework/Apollo.xcodeproj/xcshareddata/xcschemes/Apollo.xcscheme \
Carthage/Checkouts/apollo-ios-xcframework/Apollo.xcodeproj/xcshareddata/xcschemes/Apollo-Framework.xcscheme
```

Related issue https://github.com/Carthage/Carthage/issues/3358

### PR DESCRIPTION
**Pull request by BobaFetters**
Disabling automatic scheme generation for the Tuist project to resolve the issue of having duplicate schemes which are both built by Carthage.

Closes apollographql/apollo-ios#3308

### CODE REVIEW

**Review by calvincestari — CHANGES_REQUESTED** [review]
I think the two `xcuserdata/` files being modified in this changeset probably need to be manually ignored and removed from the repo; I'm surprised they're not getting caught by [the gitignore rule](https://github.com/apollographql/apollo-ios-xcframework/blob/main/.gitignore#L16).

**Comment by calvincestari** [comment]
> Disabling automatic scheme generation for the Tuist project to resolve the issue of having duplicate schemes

This continues to work because we have the single _manually_ generated schema - is that a correct understanding?

**Comment by BobaFetters** [comment]
> I think the two `xcuserdata/` files being modified in this changeset probably need to be manually ignored and removed from the repo; I'm surprised they're not getting caught by [the gitignore rule](https://github.com/apollographql/apollo-ios-xcframework/blob/main/.gitignore#L16).

Ah yea good catch, not sure why those arent getting caught by the gitignore

**Comment by BobaFetters** [comment]
> > Disabling automatic scheme generation for the Tuist project to resolve the issue of having duplicate schemes
> 
> This continues to work because we have the single _manually_ generated schema - is that a correct understanding?

Correct, in this scenario we are manually creating the necessary schemes for building the frameworks so the auto-generated schemes for the spm libraries are not needed.

**Review by calvincestari — APPROVED** [review]
LGTM!

**Pull request merged**
