### PR TITLE
Fixing issue with framework generation

### LINKED ISSUE #3427: make build-apollo-xc-framework fail with Error 70
### Summary

Following creating xcframework from https://github.com/apollographql/apollo-ios-xcframework?tab=readme-ov-file make script fail 9 times out of 10 tries with Error 70  

### Version

1.14.1

### Steps to reproduce the behavior

1. Clone repo 
2. Run make build-apollo-xc-framework

### Logs

```shell
Runing RegisterExecutionPolicyException /Users/a/Library/Developer/Xcode/DerivedData/Apollo-btbrgifwrrzzezcxjrmbkksenqto/Build/Intermediates.noindex/ArchiveIntermediates/Apollo/InstallationBuildProductsLocation/Users/a/Objects/Apollo.o (in target 'Apollo' from project 'Apollo' at path '/Users/a/Downloads/apollo-ios-xcframework-main/apollo-ios/Package.swift')
    cd /Users/a/Downloads/apollo-ios-xcframework-main/apollo-ios
    builtin-RegisterExecutionPolicyException /Users/a/Library/Developer/Xcode/DerivedData/Apollo-btbrgifwrrzzezcxjrmbkksenqto/Build/Intermediates.noindex/ArchiveIntermediates/Apollo/InstallationBuildProductsLocation/Users/a/Objects/Apollo.o

** ARCHIVE SUCCEEDED **

xcodebuild -create-xcframework -output ./build/Apollo.xcframework -framework ./build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework -framework ./build/iphoneos.xcarchive/Products/Library/Frameworks/Apollo.framework
error: the path does not point to a valid framework: /Users/a/Downloads/apollo-ios-xcframework-main/build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework
make: *** [build-apollo-xc-framework] Error 70
```

### Anything else?

Even though ** ARCHIVE SUCCEEDED ** and build folder is been created with iphoneos.xcarchive and iphonesimulator.xcarchive 
still, failure happen with [build-apollo-xc-framework] Error 70 and xcframework been created

### LINKED ISSUE #3439: apollo-ios-xcframework fails to build
### Summary

It appears that the apollo-ios-xcframework repo no longer contains any shared or generated schemes causing carthage to be unable to build.

Related to https://github.com/apollographql/apollo-ios/issues/3308

### Version

Tried with the latest version 1.15.1. Possibly occurs on older versions, we're very slow to update 🐢.

### Steps to reproduce the behavior

```bash
pushd "$(mktemp -d)" || exit
echo 'github "apollographql/apollo-ios-xcframework"' > Cartfile
carthage bootstrap
popd || exit
```

### Logs

```shell
*** No Cartfile.resolved found, updating dependencies
*** Fetching apollo-ios-xcframework
*** Checking out apollo-ios-xcframework at "1.15.1"
*** xcodebuild output can be found in /var/folders/_x/0yf9v78x1zzfd4pk03vx7f440000gq/T/carthage-xcodebuild.JiLsUV.log
*** Skipped building apollo-ios-xcframework due to the error:
Dependency "apollo-ios-xcframework" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/apollographql/apollo-ios-xcframework/issues/new
```

### Anything else?

Also, I tried manually calling the makefile to build the frameworks but that also results in an error since it appears the `iphoneos.xcarchive` doesn't contain a framework.

```shell
make build-apollo-xc-framework
```

```
xcodebuild -create-xcframework -output ./build/Apollo.xcframework -framework ./build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework -framework ./build/iphoneos.xcarchive/Products/Library/Frameworks/Apollo.framework
error: the path does not point to a valid framework: .../Carthage/Checkouts/apollo-ios-xcframework/build/iphoneos.xcarchive/Products/Library/Frameworks/Apollo.framework
make: *** [build-apollo-xc-framework] Error 70
```

I think it's also caused by there being no shared schemes. If I manually create a new scheme in the project, it shows the project targets and the package targets.

out

I'd guess the `xcodebuild` command picks the package target when specifying `-scheme Apollo` and building for iOS. After manually creating the schemes, it produces the xcframeworks.

### PR DESCRIPTION
**Pull request by BobaFetters**
Fixing an issue where the `make` command for building the apollo-ios framework was failing, also fixing issue with carthage not being able to find shared schemes to build from.

Closes apollographql/apollo-ios#3439
Closes apollographql/apollo-ios#3427

### CODE REVIEW

**Comment by CraigSiemens** [comment]
I updated the script to test it out with carthage.
```
pushd "$(mktemp -d)" || exit
echo 'github "apollographql/apollo-ios-xcframework" "fix/issue-3439"' > Cartfile
carthage bootstrap --platform iOS --use-xcframeworks
```

It appears it's building each scheme twice again because the shared scheme has the same name as scheme Xcode generates for the targets from the swift package.

Would it be possible to rename the schemes tuist generates so they are unique? Maybe adding the suffix `-xcframework`? That was the workaround I found last time. Though we'd be fine continuing to do that in our project, we've already got that code in our makefile.

- https://github.com/apollographql/apollo-ios/issues/3308
- https://github.com/Carthage/Carthage/issues/3358

**Comment by BobaFetters** [comment]
Hmmm ok, wondering if I create the xcode schemes manually in the tuist configuration and disable the auto-generation if it would avoid the issue with the spm package schemes, ill give that a shot and see, odd that `Apollo` is the only one being duplicated and not the other targets from the spm package

**Comment by BobaFetters** [comment]
Actually no that wont work at least for the duplication, but doing the schemes manually and adjusting the names as you suggested seems like a good solution.

**Comment by CraigSiemens** [comment]
Oops, I should have included the logs, it builds every target twice.
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching apollo-ios-xcframework
*** Checking out apollo-ios-xcframework at "a06f84a4ee2968f1c55dbc206b5163f441444cd1"
*** xcodebuild output can be found in /var/folders/_x/0yf9v78x1zzfd4pk03vx7f440000gq/T/carthage-xcodebuild.QilH1E.log
*** Building scheme "Apollo" in Apollo.xcworkspace
*** Building scheme "ApolloAPI" in Apollo.xcworkspace
*** Building scheme "Apollo" in Apollo.xcworkspace
*** Building scheme "ApolloAPI" in Apollo.xcworkspace
*** Building scheme "ApolloSQLite" in Apollo.xcworkspace
*** Building scheme "ApolloWebSocket" in Apollo.xcworkspace
*** Building scheme "ApolloSQLite" in Apollo.xcworkspace
*** Building scheme "ApolloWebSocket" in Apollo.xcworkspace
```

**Comment by CraigSiemens** [comment]
I also just noticed that the target for `ApolloTestSupport` isn't built. I assume it shouldn't be missing.

**Comment by BobaFetters** [comment]
@CraigSiemens ok i updated the branch tuist now generates the schemes with a suffix like you suggested and the make commands are all working so I'm guessing this will solve your Carthage issue as well.

As for `ApolloTestSupport` its currently not supported as part of the xcframework setup, although its something I can look into adding.

**Comment by CraigSiemens** [comment]
That change seems to be working, each target was built once.

```
*** No Cartfile.resolved found, updating dependencies
*** Fetching apollo-ios-xcframework
*** Checking out apollo-ios-xcframework at "5cfce4fd24fd65107e500ef2f0fc78ab3375fa94"
*** xcodebuild output can be found in /var/folders/_x/0yf9v78x1zzfd4pk03vx7f440000gq/T/carthage-xcodebuild.XGit2r.log
*** Building scheme "ApolloWebSocket-xcframework" in Apollo.xcworkspace
*** Building scheme "ApolloSQLite-xcframework" in Apollo.xcworkspace
*** Building scheme "ApolloAPI-xcframework" in Apollo.xcworkspace
*** Building scheme "Apollo-xcframework" in Apollo.xcworkspace
```

**Comment by BobaFetters** [comment]
Great, can get this merged into `main`, and it will officially release in a tagged release when we do our next `apollo-ios` release.

**Review by calvincestari — APPROVED** [review]
LGTM!

**Pull request merged**
